version: "3"

services:
  graphdb:
    container_name: graphdb-preload
    # image: ontotext/graphdb:${GRAPHDB_VERSION}-ee
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        version: ${GRAPHDB_VERSION}

    # Load all files from ../import in repo defined in ./graphdb-repo-config.ttl
    entrypoint: [ "/opt/graphdb/dist/bin/preload", "--force", "--recursive", "-c", "/root/graphdb-repo-config.ttl", "/root/graphdb-import" ]

    # Preload given file to existing repository (here "demo")
    # entrypoint: [ "/opt/graphdb/dist/bin/preload", "-f", "-i", "demo", "/root/graphdb-import" ]

    environment: 
      - GDB_HEAP_SIZE=${GRAPHDB_HEAP_SIZE}
    volumes:
      # Change folders in the .env file or directly here
      - ${IMPORT_FOLDER}:/root/graphdb-import
      - ${REPOSITORY_CONFIG_FILE}:/root/graphdb-repo-config.ttl
      - ${GRAPHDB_HOME}/data:/opt/graphdb/dist/data
      - ${GRAPHDB_HOME}/work:/opt/graphdb/dist/work
      - ${GRAPHDB_HOME}/logs:/opt/graphdb/dist/logs
